### ISSUE TITLE
Binutils version?

### ISSUE THREAD

**Issue by jwt27** [andrewwutw/build-djgpp#12]
Just noticed the script downloads and builds binutils version 2.24. I changed it to build the latest version (2.26) instead, and it seems to work fine as far as I can tell.  
Any reason to prefer the old 2.24 version?

**Comment by neta79** [comment]
As we speak, the binutils for DJGPP package v2.26 still have to be released. You might be able to build using BINUTILS_VERSION=225 though.

**Comment by andrewwutw** [comment]
No special reason. Because 2.24 worked in the past, so I am still using 2.24 now. :stuck_out_tongue:

**Comment by jwt27** [comment]
@neta79 It's on Delorie's ftp already, that's where I got it from -> ftp://ftp.delorie.com/pub/djgpp/current/v2gnu/bnu226sr3.zip

Besides, is there any difference between the djgpp release and "official" GNU release for binutils?

**Comment by andrewwutw** [comment]
@jwt27  Ok, for newer DJGPP versions in the future, I will use latest version binutils. :smile:

**Comment by pohmelie** [comment]
How can I build djgpp with 2.27 binutils? I really need it to test some issues.
https://groups.google.com/forum/#!topic/comp.os.msdos.djgpp/AwKemzSvn6A
http://www.delorie.com/pub/djgpp/current/v2gnu/bnu227s.zip
http://www.delorie.com/pub/djgpp/current/v2gnu/bnu227b.zip

**Comment by andrewwutw** [comment]
@pohmelie Yes, I tested and also encountered the same problem : undefined reference to `coff_64k_relocation_enabled' (https://groups.google.com/forum/#!msg/comp.os.msdos.djgpp/mUOzbTpE1Sk/ODqAENwlAgAJ)

I tried to patch binutils 2.27 bfd/init.c, and it seems to work. I create a branch "support-binutils-2.27" for this : https://github.com/andrewwutw/build-djgpp/tree/support-binutils-2.27

You can pull this branch, and build GCC 6.3.0 by running 

`
 ./build-djgpp.sh 6.3.0
`

Please check if it works.

**Comment by pohmelie** [comment]
@andrewwutw 
Thanks! With 2.27 binutils from your branch everything work as expected. :+1:

**Comment by andrewwutw** [comment]
@pohmelie Great, thank you. 😄
